[package]
name = "exifrs"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.5.0"
chrono = "0.4.38"
clap = "4.5.19"
colored = "2.1.0"
image = "0.25.2"
jpeg-decoder = "0.3.1"
prettytable = "0.10.0"
tiff = "0.9.1"
